# Generated by Django 5.2.5 on 2025-08-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='employee_pics/'),
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.CharField(default='New', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='part_number',
            field=models.CharField(default='000000', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
