# Generated by Django 5.2.5 on 2025-08-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customer_provider_id_customer_provider_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('provider_name', 'provider_id')},
        ),
    ]
