# Generated by Django 5.2.5 on 2025-08-15 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_part_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='repairorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='repairorder',
            name='shop',
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repairorder',
            name='parts',
            field=models.ManyToManyField(related_name='repair_orders', through='shop.RepairOrderPart', to='shop.part'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('vin', models.CharField(max_length=100, unique=True)),
                ('license_plate', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='shop.customer')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='shop.vehicle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repairorder',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='repair_orders', to='shop.vehicle'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VehicleProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='shop.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='reported_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='shop.vehicleproblem'),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='provider_name',
        ),
    ]
